INSERT INTO Publishers VALUES (1, 'Nintendo');
INSERT INTO Publishers VALUES (2, 'Microsoft Game Studios');
INSERT INTO Publishers VALUES (3, 'Take-Two Interactive');
INSERT INTO Publishers VALUES (4, 'Sony Computer Entertainment');
INSERT INTO Publishers VALUES (5, 'Activision');
INSERT INTO Publishers VALUES (6, 'Ubisoft');
INSERT INTO Publishers VALUES (7, 'Bethesda Softworks');
INSERT INTO Publishers VALUES (8, 'Electronic Arts');
INSERT INTO Publishers VALUES (9, 'Sega');
INSERT INTO Publishers VALUES (10, 'SquareSoft');
INSERT INTO Publishers VALUES (11, 'Atari');
INSERT INTO Publishers VALUES (12, '505 Games');
INSERT INTO Publishers VALUES (13, 'Capcom');
INSERT INTO Publishers VALUES (14, 'GT Interactive');
INSERT INTO Publishers VALUES (15, 'Konami Digital Entertainment');
INSERT INTO Publishers VALUES (16, 'Sony Computer Entertainment Europe');
INSERT INTO Publishers VALUES (17, 'Square Enix');
INSERT INTO Publishers VALUES (18, 'LucasArts');
INSERT INTO Publishers VALUES (19, 'Virgin Interactive');
INSERT INTO Publishers VALUES (20, 'Warner Bros. Interactive Entertainment');
INSERT INTO Publishers VALUES (21, 'Universal Interactive');
INSERT INTO Publishers VALUES (22, 'Eidos Interactive');
INSERT INTO Publishers VALUES (23, 'RedOctane');
INSERT INTO Publishers VALUES (24, 'Vivendi Games');
INSERT INTO Publishers VALUES (25, 'Enix Corporation');
INSERT INTO Publishers VALUES (26, 'Namco Bandai Games');
INSERT INTO Publishers VALUES (27, 'Palcom');
INSERT INTO Publishers VALUES (28, 'Hasbro Interactive');
INSERT INTO Publishers VALUES (29, 'THQ');
INSERT INTO Publishers VALUES (30, 'Fox Interactive');
INSERT INTO Publishers VALUES (31, 'Acclaim Entertainment');
INSERT INTO Publishers VALUES (32, 'MTV Games');
INSERT INTO Publishers VALUES (33, 'Disney Interactive Studios');
INSERT INTO Publishers VALUES (34, 'Majesco Entertainment');
INSERT INTO Publishers VALUES (35, 'Codemasters');
INSERT INTO Publishers VALUES (36, 'Red Orb');
INSERT INTO Publishers VALUES (37, 'Level 5');
INSERT INTO Publishers VALUES (38, 'Arena Entertainment');
INSERT INTO Publishers VALUES (39, 'Midway Games');
INSERT INTO Publishers VALUES (40, 'JVC');
INSERT INTO Publishers VALUES (41, 'Deep Silver');
INSERT INTO Publishers VALUES (42, '989 Studios');
INSERT INTO Publishers VALUES (43, 'NCSoft');
INSERT INTO Publishers VALUES (44, 'UEP Systems');
INSERT INTO Publishers VALUES (45, 'Parker Bros.');
INSERT INTO Publishers VALUES (46, 'Maxis');
INSERT INTO Publishers VALUES (47, 'Imagic');
INSERT INTO Publishers VALUES (48, 'Tecmo Koei');
INSERT INTO Publishers VALUES (49, 'Valve Software');
INSERT INTO Publishers VALUES (50, 'ASCII Entertainment');
INSERT INTO Publishers VALUES (51, 'Mindscape');
INSERT INTO Publishers VALUES (52, 'Infogrames');
INSERT INTO Publishers VALUES (53, 'Unknown');
INSERT INTO Publishers VALUES (54, 'Square');
INSERT INTO Publishers VALUES (55, 'Valve');
INSERT INTO Publishers VALUES (56, 'Activision Value');
INSERT INTO Publishers VALUES (57, 'Banpresto');
INSERT INTO Publishers VALUES (58, 'D3Publisher');
INSERT INTO Publishers VALUES (59, 'Oxygen Interactive');
INSERT INTO Publishers VALUES (60, 'Red Storm Entertainment');
INSERT INTO Publishers VALUES (61, 'Video System');
INSERT INTO Publishers VALUES (62, 'Hello Games');
INSERT INTO Publishers VALUES (63, 'Global Star');
INSERT INTO Publishers VALUES (64, 'Gotham Games');
INSERT INTO Publishers VALUES (65, 'Westwood Studios');
INSERT INTO Publishers VALUES (66, 'GungHo');
INSERT INTO Publishers VALUES (67, 'Crave Entertainment');
INSERT INTO Publishers VALUES (68, 'Hudson Soft');
INSERT INTO Publishers VALUES (69, 'Coleco');
INSERT INTO Publishers VALUES (70, 'Rising Star Games');
INSERT INTO Publishers VALUES (71, 'Atlus');
INSERT INTO Publishers VALUES (72, 'TDK Mediactive');
INSERT INTO Publishers VALUES (73, 'ASC Games');
INSERT INTO Publishers VALUES (74, 'Zoo Games');
INSERT INTO Publishers VALUES (75, 'Accolade');
INSERT INTO Publishers VALUES (76, 'Sony Online Entertainment');
INSERT INTO Publishers VALUES (77, '3DO');
INSERT INTO Publishers VALUES (78, 'RTL');
INSERT INTO Publishers VALUES (79, 'Natsume');
INSERT INTO Publishers VALUES (80, 'Focus Home Interactive');
INSERT INTO Publishers VALUES (81, 'Alchemist');
INSERT INTO Publishers VALUES (82, 'Black Label Games');
INSERT INTO Publishers VALUES (83, 'SouthPeak Games');
INSERT INTO Publishers VALUES (84, 'Mastertronic');
INSERT INTO Publishers VALUES (85, 'Ocean');
INSERT INTO Publishers VALUES (86, 'Zoo Digital Publishing');
INSERT INTO Publishers VALUES (87, 'Psygnosis');
INSERT INTO Publishers VALUES (88, 'City Interactive');
INSERT INTO Publishers VALUES (89, 'Empire Interactive');
INSERT INTO Publishers VALUES (90, 'Success');
INSERT INTO Publishers VALUES (91, 'Compile');
INSERT INTO Publishers VALUES (92, 'Russel');
INSERT INTO Publishers VALUES (93, 'Taito');
INSERT INTO Publishers VALUES (94, 'Agetec');
INSERT INTO Publishers VALUES (95, 'GSP');
INSERT INTO Publishers VALUES (96, 'Microprose');
INSERT INTO Publishers VALUES (97, 'Play It');
INSERT INTO Publishers VALUES (98, 'Slightly Mad Studios');
INSERT INTO Publishers VALUES (99, 'Tomy Corporation');
INSERT INTO Publishers VALUES (100, 'Sammy Corporation');
INSERT INTO Publishers VALUES (101, 'Koch Media');
INSERT INTO Publishers VALUES (102, 'Game Factory');
INSERT INTO Publishers VALUES (103, 'Titus');
INSERT INTO Publishers VALUES (104, 'Marvelous Entertainment');
INSERT INTO Publishers VALUES (105, 'Genki');
INSERT INTO Publishers VALUES (106, 'Mojang');
INSERT INTO Publishers VALUES (107, 'Pinnacle');
INSERT INTO Publishers VALUES (108, 'CTO SpA');
INSERT INTO Publishers VALUES (109, 'TalonSoft');
INSERT INTO Publishers VALUES (110, 'Crystal Dynamics');
INSERT INTO Publishers VALUES (111, 'SCi');
INSERT INTO Publishers VALUES (112, 'Quelle');
INSERT INTO Publishers VALUES (113, 'mixi, Inc');
INSERT INTO Publishers VALUES (114, 'Rage Software');
INSERT INTO Publishers VALUES (115, 'Ubisoft Annecy');
INSERT INTO Publishers VALUES (116, 'Scholastic Inc.');
INSERT INTO Publishers VALUES (117, 'Interplay');
INSERT INTO Publishers VALUES (118, 'Mystique');
INSERT INTO Publishers VALUES (119, 'ChunSoft');
INSERT INTO Publishers VALUES (120, 'Square EA');
INSERT INTO Publishers VALUES (121, '20th Century Fox Video Games');
INSERT INTO Publishers VALUES (122, 'Avanquest Software');
INSERT INTO Publishers VALUES (123, 'Hudson Entertainment');
INSERT INTO Publishers VALUES (124, 'Nordic Games');
INSERT INTO Publishers VALUES (125, 'Men-A-Vision');
INSERT INTO Publishers VALUES (126, 'Nobilis');
INSERT INTO Publishers VALUES (127, 'Big Ben Interactive');
INSERT INTO Publishers VALUES (128, 'Touchstone');
INSERT INTO Publishers VALUES (129, 'Spike');
INSERT INTO Publishers VALUES (130, 'Jester Interactive');
INSERT INTO Publishers VALUES (131, 'Nippon Ichi Software');
INSERT INTO Publishers VALUES (132, 'LEGO Media');
INSERT INTO Publishers VALUES (133, 'Quest');
INSERT INTO Publishers VALUES (134, 'Illusion Softworks');
INSERT INTO Publishers VALUES (135, 'Tigervision');
INSERT INTO Publishers VALUES (136, 'Funbox Media');
INSERT INTO Publishers VALUES (137, 'Rocket Company');
INSERT INTO Publishers VALUES (138, 'Metro 3D');
INSERT INTO Publishers VALUES (139, 'Mattel Interactive');
INSERT INTO Publishers VALUES (140, 'IE Institute');
INSERT INTO Publishers VALUES (141, 'Rondomedia');
INSERT INTO Publishers VALUES (142, 'Sony Computer Entertainment America');
INSERT INTO Publishers VALUES (143, 'Universal Gamex');
INSERT INTO Publishers VALUES (144, 'Ghostlight');
INSERT INTO Publishers VALUES (145, 'Wizard Video Games');
INSERT INTO Publishers VALUES (146, 'BMG Interactive Entertainment');
INSERT INTO Publishers VALUES (147, 'PQube');
INSERT INTO Publishers VALUES (148, 'Trion Worlds');
INSERT INTO Publishers VALUES (149, 'Laguna');
INSERT INTO Publishers VALUES (150, 'Ignition Entertainment');
INSERT INTO Publishers VALUES (151, 'Takara');
INSERT INTO Publishers VALUES (152, 'Kadokawa Shoten');
INSERT INTO Publishers VALUES (153, 'Destineer');
INSERT INTO Publishers VALUES (154, 'Enterbrain');
INSERT INTO Publishers VALUES (155, 'Xseed Games');
INSERT INTO Publishers VALUES (156, 'Imagineer');
INSERT INTO Publishers VALUES (157, 'System 3 Arcade Software');
INSERT INTO Publishers VALUES (158, 'CPG Products');
INSERT INTO Publishers VALUES (159, 'Aruze Corp');
INSERT INTO Publishers VALUES (160, 'Gamebridge');
INSERT INTO Publishers VALUES (161, 'Midas Interactive Entertainment');
INSERT INTO Publishers VALUES (162, 'Jaleco');
INSERT INTO Publishers VALUES (163, 'Answer Software');
INSERT INTO Publishers VALUES (164, 'XS Games');
INSERT INTO Publishers VALUES (165, 'Activision Blizzard');
INSERT INTO Publishers VALUES (166, 'Pack In Soft');
INSERT INTO Publishers VALUES (167, 'Rebellion');
INSERT INTO Publishers VALUES (168, 'Xplosiv');
INSERT INTO Publishers VALUES (169, 'Ultravision');
INSERT INTO Publishers VALUES (170, 'GameMill Entertainment');
INSERT INTO Publishers VALUES (171, 'Wanadoo');
INSERT INTO Publishers VALUES (172, 'NovaLogic');
INSERT INTO Publishers VALUES (173, 'Telltale Games');
INSERT INTO Publishers VALUES (174, 'Epoch');
INSERT INTO Publishers VALUES (175, 'BAM! Entertainment');
INSERT INTO Publishers VALUES (176, 'Knowledge Adventure');
INSERT INTO Publishers VALUES (177, 'Mastiff');
INSERT INTO Publishers VALUES (178, 'Tetris Online');
INSERT INTO Publishers VALUES (179, 'Harmonix Music Systems');
INSERT INTO Publishers VALUES (180, 'ESP');
INSERT INTO Publishers VALUES (181, 'TYO');
INSERT INTO Publishers VALUES (182, 'Telegames');
INSERT INTO Publishers VALUES (183, 'Mud Duck Productions');
INSERT INTO Publishers VALUES (184, 'Screenlife');
INSERT INTO Publishers VALUES (185, 'Pioneer LDC');
INSERT INTO Publishers VALUES (186, 'Magical Company');
INSERT INTO Publishers VALUES (187, 'Mentor Interactive');
INSERT INTO Publishers VALUES (188, 'Kemco');
INSERT INTO Publishers VALUES (189, 'Human Entertainment');
INSERT INTO Publishers VALUES (190, 'Avanquest');
INSERT INTO Publishers VALUES (191, 'Data Age');
INSERT INTO Publishers VALUES (192, 'Electronic Arts Victor');
INSERT INTO Publishers VALUES (193, 'Black Bean Games');
INSERT INTO Publishers VALUES (194, 'Jack of All Games');
INSERT INTO Publishers VALUES (195, '989 Sports');
INSERT INTO Publishers VALUES (196, 'Takara Tomy');
INSERT INTO Publishers VALUES (197, 'Media Rings');
INSERT INTO Publishers VALUES (198, 'Elf');
INSERT INTO Publishers VALUES (199, 'Kalypso Media');
INSERT INTO Publishers VALUES (200, 'Starfish');
INSERT INTO Publishers VALUES (201, 'Zushi Games');
INSERT INTO Publishers VALUES (202, 'Jorudan');
INSERT INTO Publishers VALUES (203, 'Destination Software, Inc');
INSERT INTO Publishers VALUES (204, 'New');
INSERT INTO Publishers VALUES (205, 'Brash Entertainment');
INSERT INTO Publishers VALUES (206, 'ITT Family Games');
INSERT INTO Publishers VALUES (207, 'PopCap Games');
INSERT INTO Publishers VALUES (208, 'Home Entertainment Suppliers');
INSERT INTO Publishers VALUES (209, 'Ackkstudios');
INSERT INTO Publishers VALUES (210, 'Starpath Corp.');
INSERT INTO Publishers VALUES (211, 'P2 Games');
INSERT INTO Publishers VALUES (212, 'BPS');
INSERT INTO Publishers VALUES (213, 'Gathering of Developers');
INSERT INTO Publishers VALUES (214, 'NewKidCo');
INSERT INTO Publishers VALUES (215, 'Storm City Games');
INSERT INTO Publishers VALUES (216, 'CokeM Interactive');
INSERT INTO Publishers VALUES (217, 'CBS Electronics');
INSERT INTO Publishers VALUES (218, 'Magix');
INSERT INTO Publishers VALUES (219, 'Marvelous Interactive');
INSERT INTO Publishers VALUES (220, 'Nihon Falcom Corporation');
INSERT INTO Publishers VALUES (221, 'Wargaming.net');
INSERT INTO Publishers VALUES (222, 'Angel Studios');
INSERT INTO Publishers VALUES (223, 'Arc System Works');
INSERT INTO Publishers VALUES (224, 'Playmates');
INSERT INTO Publishers VALUES (225, 'SNK Playmore');
INSERT INTO Publishers VALUES (226, 'Hamster Corporation');
INSERT INTO Publishers VALUES (227, 'From Software');
INSERT INTO Publishers VALUES (228, 'Nippon Columbia');
INSERT INTO Publishers VALUES (229, 'Nichibutsu');
INSERT INTO Publishers VALUES (230, 'Little Orbit');
INSERT INTO Publishers VALUES (231, 'Conspiracy Entertainment');
INSERT INTO Publishers VALUES (232, 'DTP Entertainment');
INSERT INTO Publishers VALUES (233, 'Hect');
INSERT INTO Publishers VALUES (234, 'Mumbo Jumbo');
INSERT INTO Publishers VALUES (235, 'Pacific Century Cyber Works');
INSERT INTO Publishers VALUES (236, 'Indie Games');
INSERT INTO Publishers VALUES (237, 'Liquid Games');
INSERT INTO Publishers VALUES (238, 'NEC');
INSERT INTO Publishers VALUES (239, 'Axela');
INSERT INTO Publishers VALUES (240, 'ArtDink');
INSERT INTO Publishers VALUES (241, 'Sunsoft');
INSERT INTO Publishers VALUES (242, 'Gust');
INSERT INTO Publishers VALUES (243, 'SNK');
INSERT INTO Publishers VALUES (244, 'NEC Interchannel');
INSERT INTO Publishers VALUES (245, 'FuRyu');
INSERT INTO Publishers VALUES (246, 'Xing Entertainment');
INSERT INTO Publishers VALUES (247, 'ValuSoft');
INSERT INTO Publishers VALUES (248, 'Victor Interactive');
INSERT INTO Publishers VALUES (249, 'Detn8 Games');
INSERT INTO Publishers VALUES (250, 'American Softworks');
INSERT INTO Publishers VALUES (251, 'Nordcurrent');
INSERT INTO Publishers VALUES (252, 'Bomb');
INSERT INTO Publishers VALUES (253, 'Falcom Corporation');
INSERT INTO Publishers VALUES (254, 'AQ Interactive');
INSERT INTO Publishers VALUES (255, 'CCP');
INSERT INTO Publishers VALUES (256, 'Milestone S.r.l.');
INSERT INTO Publishers VALUES (257, 'Sears');
INSERT INTO Publishers VALUES (258, 'JoWood Productions');
INSERT INTO Publishers VALUES (259, 'Seta Corporation');
INSERT INTO Publishers VALUES (260, 'On Demand');
INSERT INTO Publishers VALUES (261, 'NCS');
INSERT INTO Publishers VALUES (262, 'Aspyr');
INSERT INTO Publishers VALUES (263, 'Gremlin Interactive Ltd');
INSERT INTO Publishers VALUES (264, 'Agatsuma Entertainment');
INSERT INTO Publishers VALUES (265, 'Compile Heart');
INSERT INTO Publishers VALUES (266, 'Culture Brain');
INSERT INTO Publishers VALUES (267, 'Mad Catz');
INSERT INTO Publishers VALUES (268, 'Shogakukan');
INSERT INTO Publishers VALUES (269, 'Merscom LLC');
INSERT INTO Publishers VALUES (270, 'Rebellion Developments');
INSERT INTO Publishers VALUES (271, 'Nippon Telenet');
INSERT INTO Publishers VALUES (272, 'TDK Core');
INSERT INTO Publishers VALUES (273, 'bitComposer Games');
INSERT INTO Publishers VALUES (274, 'Foreign Media Games');
INSERT INTO Publishers VALUES (275, 'Astragon');
INSERT INTO Publishers VALUES (276, 'SSI');
INSERT INTO Publishers VALUES (277, 'Kadokawa Games');
INSERT INTO Publishers VALUES (278, 'Idea Factory');
INSERT INTO Publishers VALUES (279, 'Performance Designed Products');
INSERT INTO Publishers VALUES (280, 'Asylum Entertainment');
INSERT INTO Publishers VALUES (281, 'Core Design Ltd.');
INSERT INTO Publishers VALUES (282, 'PlayV');
INSERT INTO Publishers VALUES (283, 'UFO Interactive');
INSERT INTO Publishers VALUES (284, 'Idea Factory International');
INSERT INTO Publishers VALUES (285, 'Playlogic Game Factory');
INSERT INTO Publishers VALUES (286, 'Essential Games');
INSERT INTO Publishers VALUES (287, 'Adeline Software');
INSERT INTO Publishers VALUES (288, 'Funcom');
INSERT INTO Publishers VALUES (289, 'Panther Software');
INSERT INTO Publishers VALUES (290, 'Blast! Entertainment Ltd');
INSERT INTO Publishers VALUES (291, 'Game Life');
INSERT INTO Publishers VALUES (292, 'DSI Games');
INSERT INTO Publishers VALUES (293, 'Avalon Interactive');
INSERT INTO Publishers VALUES (294, 'Popcorn Arcade');
INSERT INTO Publishers VALUES (295, 'Neko Entertainment');
INSERT INTO Publishers VALUES (296, 'Vir2L Studios');
INSERT INTO Publishers VALUES (297, 'Aques');
INSERT INTO Publishers VALUES (298, 'Syscom');
INSERT INTO Publishers VALUES (299, 'White Park Bay Software');
INSERT INTO Publishers VALUES (300, 'System 3');
INSERT INTO Publishers VALUES (301, 'Vatical Entertainment');
INSERT INTO Publishers VALUES (302, 'Daedalic');
INSERT INTO Publishers VALUES (303, 'EA Games');
INSERT INTO Publishers VALUES (304, 'Media Factory');
INSERT INTO Publishers VALUES (305, 'Vic Tokai');
INSERT INTO Publishers VALUES (306, 'The Adventure Company');
INSERT INTO Publishers VALUES (307, 'Game Arts');
INSERT INTO Publishers VALUES (308, 'Broccoli');
INSERT INTO Publishers VALUES (309, 'Acquire');
INSERT INTO Publishers VALUES (310, 'General Entertainment');
INSERT INTO Publishers VALUES (311, 'Excalibur Publishing');
INSERT INTO Publishers VALUES (312, 'Imadio');
INSERT INTO Publishers VALUES (313, 'Swing! Entertainment');
INSERT INTO Publishers VALUES (314, 'Sony Music Entertainment');
INSERT INTO Publishers VALUES (315, 'Aqua Plus');
INSERT INTO Publishers VALUES (316, 'Paradox Interactive');
INSERT INTO Publishers VALUES (317, 'Hip Interactive');
INSERT INTO Publishers VALUES (318, 'DreamCatcher Interactive');
INSERT INTO Publishers VALUES (319, 'Tripwire Interactive');
INSERT INTO Publishers VALUES (320, 'Sting');
INSERT INTO Publishers VALUES (321, 'Yacht Club Games');
INSERT INTO Publishers VALUES (322, 'SCS Software');
INSERT INTO Publishers VALUES (323, 'Bigben Interactive');
INSERT INTO Publishers VALUES (324, 'Havas Interactive');
INSERT INTO Publishers VALUES (325, 'Slitherine Software');
INSERT INTO Publishers VALUES (326, 'Graffiti');
INSERT INTO Publishers VALUES (327, 'Funsta');
INSERT INTO Publishers VALUES (328, 'Telstar');
INSERT INTO Publishers VALUES (329, 'U.S. Gold');
INSERT INTO Publishers VALUES (330, 'DreamWorks Interactive');
INSERT INTO Publishers VALUES (331, 'Data Design Interactive');
INSERT INTO Publishers VALUES (332, 'MTO');
INSERT INTO Publishers VALUES (333, 'DHM Interactive');
INSERT INTO Publishers VALUES (334, 'FunSoft');
INSERT INTO Publishers VALUES (335, 'SPS');
INSERT INTO Publishers VALUES (336, 'Bohemia Interactive');
INSERT INTO Publishers VALUES (337, 'Reef Entertainment');
INSERT INTO Publishers VALUES (338, 'Tru Blu Entertainment');
INSERT INTO Publishers VALUES (339, 'Moss');
INSERT INTO Publishers VALUES (340, 'T&E Soft');
INSERT INTO Publishers VALUES (341, 'O-Games');
INSERT INTO Publishers VALUES (342, 'Aksys Games');
INSERT INTO Publishers VALUES (343, 'NDA Productions');
INSERT INTO Publishers VALUES (344, 'Data East');
INSERT INTO Publishers VALUES (345, 'Time Warner Interactive');
INSERT INTO Publishers VALUES (346, 'Gainax Network Systems');
INSERT INTO Publishers VALUES (347, 'Daito');
INSERT INTO Publishers VALUES (348, 'O3 Entertainment');
INSERT INTO Publishers VALUES (349, 'Gameloft');
INSERT INTO Publishers VALUES (350, 'Xicat Interactive');
INSERT INTO Publishers VALUES (351, 'Simon & Schuster Interactive');
INSERT INTO Publishers VALUES (352, 'Valcon Games');
INSERT INTO Publishers VALUES (353, 'PopTop Software');
INSERT INTO Publishers VALUES (354, 'TOHO');
INSERT INTO Publishers VALUES (355, 'HMH Interactive');
INSERT INTO Publishers VALUES (356, '5pb');
INSERT INTO Publishers VALUES (357, 'Cave');
INSERT INTO Publishers VALUES (358, 'CDV Software Entertainment');
INSERT INTO Publishers VALUES (359, 'Microids');
INSERT INTO Publishers VALUES (360, 'PM Studios');
INSERT INTO Publishers VALUES (361, 'Paon');
INSERT INTO Publishers VALUES (362, 'Micro Cabin');
INSERT INTO Publishers VALUES (363, 'GameTek');
INSERT INTO Publishers VALUES (364, 'Benesse');
INSERT INTO Publishers VALUES (365, 'Type-Moon');
INSERT INTO Publishers VALUES (366, 'Enjoy Gaming ltd.');
INSERT INTO Publishers VALUES (367, 'Asmik Corp');
INSERT INTO Publishers VALUES (368, 'Interplay Productions');
INSERT INTO Publishers VALUES (369, 'Asmik Ace Entertainment');
INSERT INTO Publishers VALUES (370, 'inXile Entertainment');
INSERT INTO Publishers VALUES (371, 'Image Epoch');
INSERT INTO Publishers VALUES (372, 'Phantom EFX');
INSERT INTO Publishers VALUES (373, 'Evolved Games');
INSERT INTO Publishers VALUES (374, 'responDESIGN');
INSERT INTO Publishers VALUES (375, 'Culture Publishers');
INSERT INTO Publishers VALUES (376, 'Griffin International');
INSERT INTO Publishers VALUES (377, 'Hackberry');
INSERT INTO Publishers VALUES (378, 'Hearty Robin');
INSERT INTO Publishers VALUES (379, 'Nippon Amuse');
INSERT INTO Publishers VALUES (380, 'Origin Systems');
INSERT INTO Publishers VALUES (381, 'Seventh Chord');
INSERT INTO Publishers VALUES (382, 'Mitsui');
INSERT INTO Publishers VALUES (383, 'Milestone');
INSERT INTO Publishers VALUES (384, 'Abylight');
INSERT INTO Publishers VALUES (385, 'Flight-Plan');
INSERT INTO Publishers VALUES (386, 'Glams');
INSERT INTO Publishers VALUES (387, 'Locus');
INSERT INTO Publishers VALUES (388, 'Warp');
INSERT INTO Publishers VALUES (389, 'Daedalic Entertainment');
INSERT INTO Publishers VALUES (390, 'Alternative Software');
INSERT INTO Publishers VALUES (391, 'Myelin Media');
INSERT INTO Publishers VALUES (392, 'Mercury Games');
INSERT INTO Publishers VALUES (393, 'Irem Software Engineering');
INSERT INTO Publishers VALUES (394, 'Sunrise Interactive');
INSERT INTO Publishers VALUES (395, 'Elite');
INSERT INTO Publishers VALUES (396, 'Evolution Games');
INSERT INTO Publishers VALUES (397, 'Tivola');
INSERT INTO Publishers VALUES (398, 'Global A Entertainment');
INSERT INTO Publishers VALUES (399, 'Edia');
INSERT INTO Publishers VALUES (400, 'Athena');
INSERT INTO Publishers VALUES (401, 'Aria');
INSERT INTO Publishers VALUES (402, 'Gamecock');
INSERT INTO Publishers VALUES (403, 'Tommo');
INSERT INTO Publishers VALUES (404, 'Altron');
INSERT INTO Publishers VALUES (405, 'Happinet');
INSERT INTO Publishers VALUES (406, 'iWin');
INSERT INTO Publishers VALUES (407, 'Media Works');
INSERT INTO Publishers VALUES (408, 'Fortyfive');
INSERT INTO Publishers VALUES (409, 'Revolution Software');
INSERT INTO Publishers VALUES (410, 'Imax');
INSERT INTO Publishers VALUES (411, 'Crimson Cow');
INSERT INTO Publishers VALUES (412, '10TACLE Studios');
INSERT INTO Publishers VALUES (413, 'Groove Games');
INSERT INTO Publishers VALUES (414, 'Pack-In-Video');
INSERT INTO Publishers VALUES (415, 'Insomniac Games');
INSERT INTO Publishers VALUES (416, 'Ascaron Entertainment GmbH');
INSERT INTO Publishers VALUES (417, 'Asgard');
INSERT INTO Publishers VALUES (418, 'Ecole');
INSERT INTO Publishers VALUES (419, 'Yumedia');
INSERT INTO Publishers VALUES (420, 'Phenomedia');
INSERT INTO Publishers VALUES (421, 'HAL Laboratory');
INSERT INTO Publishers VALUES (422, 'Grand Prix Games');
INSERT INTO Publishers VALUES (423, 'DigiCube');
INSERT INTO Publishers VALUES (424, 'Creative Core');
INSERT INTO Publishers VALUES (425, 'Kaga Create');
INSERT INTO Publishers VALUES (426, 'WayForward Technologies');
INSERT INTO Publishers VALUES (427, 'LSP Games');
INSERT INTO Publishers VALUES (428, 'ASCII Media Works');
INSERT INTO Publishers VALUES (429, 'Coconuts Japan');
INSERT INTO Publishers VALUES (430, 'Arika');
INSERT INTO Publishers VALUES (431, 'Ertain');
INSERT INTO Publishers VALUES (432, 'Marvel Entertainment');
INSERT INTO Publishers VALUES (433, 'Prototype');
INSERT INTO Publishers VALUES (434, 'TopWare Interactive');
INSERT INTO Publishers VALUES (435, 'Phantagram');
INSERT INTO Publishers VALUES (436, '1C Company');
INSERT INTO Publishers VALUES (437, 'The Learning Company');
INSERT INTO Publishers VALUES (438, 'TechnoSoft');
INSERT INTO Publishers VALUES (439, 'Vap');
INSERT INTO Publishers VALUES (440, 'Misawa');
INSERT INTO Publishers VALUES (441, 'Tradewest');
INSERT INTO Publishers VALUES (442, 'Team17 Software');
INSERT INTO Publishers VALUES (443, 'Yeti');
INSERT INTO Publishers VALUES (444, 'Pow');
INSERT INTO Publishers VALUES (445, 'Navarre Corp');
INSERT INTO Publishers VALUES (446, 'MediaQuest');
INSERT INTO Publishers VALUES (447, 'Max Five');
INSERT INTO Publishers VALUES (448, 'Comfort');
INSERT INTO Publishers VALUES (449, 'Monte Christo Multimedia');
INSERT INTO Publishers VALUES (450, 'Pony Canyon');
INSERT INTO Publishers VALUES (451, 'Riverhillsoft');
INSERT INTO Publishers VALUES (452, 'Summitsoft');
INSERT INTO Publishers VALUES (453, 'Milestone S.r.l');
INSERT INTO Publishers VALUES (454, 'Playmore');
INSERT INTO Publishers VALUES (455, 'MLB.com');
INSERT INTO Publishers VALUES (456, 'Kool Kizz');
INSERT INTO Publishers VALUES (457, 'Flashpoint Games');
INSERT INTO Publishers VALUES (458, '49Games');
INSERT INTO Publishers VALUES (459, 'Legacy Interactive');
INSERT INTO Publishers VALUES (460, 'Alawar Entertainment');
INSERT INTO Publishers VALUES (461, 'CyberFront');
INSERT INTO Publishers VALUES (462, 'Cloud Imperium Games Corporation');
INSERT INTO Publishers VALUES (463, 'Societa');
INSERT INTO Publishers VALUES (464, 'Virtual Play Games');
INSERT INTO Publishers VALUES (465, 'Interchannel');
INSERT INTO Publishers VALUES (466, 'Sonnet');
INSERT INTO Publishers VALUES (467, 'Experience Inc.');
INSERT INTO Publishers VALUES (468, 'Zenrin');
INSERT INTO Publishers VALUES (469, 'Iceberg Interactive');
INSERT INTO Publishers VALUES (470, 'Ivolgamus');
INSERT INTO Publishers VALUES (471, '2D Boy');
INSERT INTO Publishers VALUES (472, 'MC2 Entertainment');
INSERT INTO Publishers VALUES (473, 'Kando Games');
INSERT INTO Publishers VALUES (474, 'Just Flight');
INSERT INTO Publishers VALUES (475, 'Office Create');
INSERT INTO Publishers VALUES (476, 'Mamba Games');
INSERT INTO Publishers VALUES (477, 'Fields');
INSERT INTO Publishers VALUES (478, 'Princess Soft');
INSERT INTO Publishers VALUES (479, 'Maximum Family Games');
INSERT INTO Publishers VALUES (480, 'Berkeley');
INSERT INTO Publishers VALUES (481, 'Fuji');
INSERT INTO Publishers VALUES (482, 'Dusenberry Martin Racing');
INSERT INTO Publishers VALUES (483, 'imageepoch Inc.');
INSERT INTO Publishers VALUES (484, 'Big Fish Games');
INSERT INTO Publishers VALUES (485, 'Her Interactive');
INSERT INTO Publishers VALUES (486, 'Kamui');
INSERT INTO Publishers VALUES (487, 'ASK');
INSERT INTO Publishers VALUES (488, 'Headup Games');
INSERT INTO Publishers VALUES (489, 'KSS');
INSERT INTO Publishers VALUES (490, 'Cygames');
INSERT INTO Publishers VALUES (491, 'KID');
INSERT INTO Publishers VALUES (492, 'Quinrose');
INSERT INTO Publishers VALUES (493, 'Sunflowers');
INSERT INTO Publishers VALUES (494, 'dramatic create');
INSERT INTO Publishers VALUES (495, 'TGL');
INSERT INTO Publishers VALUES (496, 'Encore');
INSERT INTO Publishers VALUES (497, 'Extreme Entertainment Group');
INSERT INTO Publishers VALUES (498, 'Intergrow');
INSERT INTO Publishers VALUES (499, 'G.Rev');
INSERT INTO Publishers VALUES (500, 'Sweets');
INSERT INTO Publishers VALUES (501, 'Kokopeli Digital Studios');
INSERT INTO Publishers VALUES (502, 'Number None');
INSERT INTO Publishers VALUES (503, 'Nexon');
INSERT INTO Publishers VALUES (504, 'id Software');
INSERT INTO Publishers VALUES (505, 'BushiRoad');
INSERT INTO Publishers VALUES (506, 'Tryfirst');
INSERT INTO Publishers VALUES (507, 'Strategy First');
INSERT INTO Publishers VALUES (508, '7G//AMES');
INSERT INTO Publishers VALUES (509, 'GN Software');
INSERT INTO Publishers VALUES (510, 'Yuke''s');
INSERT INTO Publishers VALUES (511, 'Easy Interactive');
INSERT INTO Publishers VALUES (512, 'Licensed 4U');
INSERT INTO Publishers VALUES (513, 'FuRyu Corporation');
INSERT INTO Publishers VALUES (514, 'Lexicon Entertainment');
INSERT INTO Publishers VALUES (515, 'Paon Corporation');
INSERT INTO Publishers VALUES (516, 'Kids Station');
INSERT INTO Publishers VALUES (517, 'GOA');
INSERT INTO Publishers VALUES (518, 'Graphsim Entertainment');
INSERT INTO Publishers VALUES (519, 'King Records');
INSERT INTO Publishers VALUES (520, 'Introversion Software');
INSERT INTO Publishers VALUES (521, 'Minato Station');
INSERT INTO Publishers VALUES (522, 'Devolver Digital');
INSERT INTO Publishers VALUES (523, 'Blue Byte');
INSERT INTO Publishers VALUES (524, 'Gaga');
INSERT INTO Publishers VALUES (525, 'Yamasa Entertainment');
INSERT INTO Publishers VALUES (526, 'Plenty');
INSERT INTO Publishers VALUES (527, 'Views');
INSERT INTO Publishers VALUES (528, 'fonfun');
INSERT INTO Publishers VALUES (529, 'NetRevo');
INSERT INTO Publishers VALUES (530, 'Codemasters Online');
INSERT INTO Publishers VALUES (531, 'Quintet');
INSERT INTO Publishers VALUES (532, 'Phoenix Games');
INSERT INTO Publishers VALUES (533, 'Dorart');
INSERT INTO Publishers VALUES (534, 'Marvelous Games');
INSERT INTO Publishers VALUES (535, 'Focus Multimedia');
INSERT INTO Publishers VALUES (536, 'Imageworks');
INSERT INTO Publishers VALUES (537, 'Karin Entertainment');
INSERT INTO Publishers VALUES (538, 'Aerosoft');
INSERT INTO Publishers VALUES (539, 'Technos Japan Corporation');
INSERT INTO Publishers VALUES (540, 'Gakken');
INSERT INTO Publishers VALUES (541, 'Mirai Shounen');
INSERT INTO Publishers VALUES (542, 'Datam Polystar');
INSERT INTO Publishers VALUES (543, 'Saurus');
INSERT INTO Publishers VALUES (544, 'HuneX');
INSERT INTO Publishers VALUES (545, 'Revolution (Japan)');
INSERT INTO Publishers VALUES (546, 'Giza10');
INSERT INTO Publishers VALUES (547, 'Visco');
INSERT INTO Publishers VALUES (548, 'Alvion');
INSERT INTO Publishers VALUES (549, 'Mycom');
INSERT INTO Publishers VALUES (550, 'Giga');
INSERT INTO Publishers VALUES (551, 'Warashi');
INSERT INTO Publishers VALUES (552, 'System Soft');
INSERT INTO Publishers VALUES (553, 'Sold Out');
INSERT INTO Publishers VALUES (554, 'Lighthouse Interactive');
INSERT INTO Publishers VALUES (555, 'Masque Publishing');
INSERT INTO Publishers VALUES (556, 'RED Entertainment');
INSERT INTO Publishers VALUES (557, 'Michaelsoft');
INSERT INTO Publishers VALUES (558, 'Media Entertainment');
INSERT INTO Publishers VALUES (559, 'New World Computing');
INSERT INTO Publishers VALUES (560, 'Genterprise');
INSERT INTO Publishers VALUES (561, 'Interworks Unlimited, Inc.');
INSERT INTO Publishers VALUES (562, 'Boost On');
INSERT INTO Publishers VALUES (563, 'Stainless Games');
INSERT INTO Publishers VALUES (564, 'EON Digital Entertainment');
INSERT INTO Publishers VALUES (565, 'Epic Games');
INSERT INTO Publishers VALUES (566, 'Naxat Soft');
INSERT INTO Publishers VALUES (567, 'Ascaron Entertainment');
INSERT INTO Publishers VALUES (568, 'Piacci');
INSERT INTO Publishers VALUES (569, 'Nitroplus');
INSERT INTO Publishers VALUES (570, 'Paradox Development');
INSERT INTO Publishers VALUES (571, 'Otomate');
INSERT INTO Publishers VALUES (572, 'Ongakukan');
INSERT INTO Publishers VALUES (573, 'Commseed');
INSERT INTO Publishers VALUES (574, 'Inti Creates');
INSERT INTO Publishers VALUES (575, 'Takuyo');
INSERT INTO Publishers VALUES (576, 'Interchannel-Holon');
INSERT INTO Publishers VALUES (577, 'Rain Games');
INSERT INTO Publishers VALUES (578, 'UIG Entertainment');